services:
  frontend:
    image: ghcr.io/eyaldassa/water-switch-ui-frontend:0.1.0
    expose:
      - '80'
    depends_on:
      - backend
    networks:
      - default
      - nginx-reverse-proxy_default
  backend:
    image: ghcr.io/eyaldassa/water-switch-ui-backend:0.1.0
    expose:
      - '3001'
    networks:
      - default
      - nginx-reverse-proxy_default
    environment:
      - ACCESS_ID=${ACCESS_ID}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - DEVICE_ID=${DEVICE_ID}
      - TUYA_REGION=${TUYA_REGION}
      - HOME_ID=${HOME_ID}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - PORT=3001
      - TZ=Asia/Jerusalem
    volumes:
      - /etc/localtime:/etc/localtime:ro
networks:
  nginx-reverse-proxy_default:
    external: true
